###
GET http://localhost:8080/user

###
GET http://localhost:8080/todo


### 全文一致
GET http://localhost:8080/todo?userId=1&title=Finish the tutorial on Quarkus framework


### あいまい検索
GET http://localhost:8080/todo?userId=1&title=Finish
###
POST http://localhost:8080/todo
Content-Type:application/json

{
    "task": "aaa",
    "registerDate": "2020-04-01"
}

###
PUT http://localhost:8080/todo/4
Content-Type:application/json

{
    "taskId": "4",
    "task": "ccc",
    "registerDate": "2020-04-01"
}

###
DELETE http://localhost:8080/todo/4
Content-Type:application/json

