###
GET http://localhost:8080/user

###
GET http://localhost:8080/project

###
GET http://localhost:8080/project?userId=1


###
GET http://localhost:8080/project?userId=2

### 全文一致
GET http://localhost:8080/project?userId=1&title=Finish the tutorial on Quarkus framework

### 全文一致(titleが文字列のnull
GET http://localhost:8080/project?userId=1&title=null


### あいまい検索
GET http://localhost:8080/project?userId=1&title=Finish
###
POST http://localhost:8080/project
Content-Type:application/json

{
    "userId": 1,
    "title": "aaa",
    "registerDate": "2020-04-01",
    "detailList": [
        {
            "taskName": "taskNameExample"
        }
    ]
    
}

###
PUT http://localhost:8080/project/user/1/task/1
Content-Type:application/json

{
    "title": "ccc"
}

###
DELETE http://localhost:8080/project/4
Content-Type:application/json



###
PATCH http://localhost:8080/project/taskId/1?statusDivision=0
Content-Type:application/json