generatorName: jaxrs-spec
library: quarkus
inputSpec: /local/openapi/poc_openapi.yaml
outputDir: /local/out/jaxrs-spec
additionalProperties:
  dateLibrary:: java8-localdatetime
  hideGenerationTimestamp: true
  openApiNullable: false
  useBeanValidation: true
  useRuntimeException: true
  microprofileRestClientVersion: "3.0"
  serializationLibrary: "jackson"
  useJakartaEe: true
  generateBuilders: true
  interfaceOnly: true
  useSwaggerAnnotations: false
  useMicroProfileOpenAPIAnnotations: false