openapi: 3.0.0
info:
  title: Project API
  description: This API allows you to manage user's project data.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /project:
    get:
      summary: Get user's pet by user ID and pet ID
      operationId: getList
      responses:
        "200":
          description: A list of projects
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Projects"
    post:
      summary: Create a new project
      operationId: create
      requestBody:
        description: Project object that needs to be added
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Project"
      responses:
        "201":
          description: No Content

  /projects/{projectId}/taskId/{taskId}:
    patch:
      summary: update a task status
      operationId: updateTaskStatus
      requestBody:
        description: Task object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/ApprovalReqBody"
      responses:
        "204":
          description: No Content

components:
  requestBodies:
    ApprovalReqBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              taskStatus:
                $ref: "#/components/schemas/TaskStatus"
            required:
              - taskStatus

  schemas:
    Projects:
      type: array
      items:
        $ref: "#/components/schemas/Project"

    Project:
      type: object
      description: A project object
      properties:
        projectId:
          type: integer
          format: int64
          description: The unique identifier for a project
        userId:
          type: integer
          format: int64
          description: The unique identifier for a user
        title:
          type: string
          description: The title of the project
        registerDate:
          type: string
          format: date-time
          description: The date the project was registered
        taskList:
          type: array
          items:
            $ref: "#/components/schemas/Task"

    Task:
      type: object
      description: A task object
      properties:
        taskId:
          type: integer
          format: int64
          description: The unique identifier for a task
        parentProjectId:
          type: integer
          format: int64
          description: The unique identifier for a project
        taskName:
          type: string
          description: The name of the task
        TaskStatus:
          $ref: "#/components/schemas/TaskStatus"

    TaskStatus:
      type: string
      description: The status of the task
      enum:
        - NOT_STARTED
        - IN_PROGRESS
        - COMPLETED
