### プロジェクト一覧取得
GET http://localhost:8080/project?userId=1
X-User-Id: 1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJ1cG4iOiIyIiwiZ3JvdXBzIjpbIlVTRVIiXSwiZXhwIjoxNzU3OTQ3OTIxLCJpYXQiOjE3NTc5NDQzMjEsImp0aSI6ImQ0ZDFiN2MzLWJkMmUtNGI3MS1hOTI1LTA5YWE2MjI1OTJiZSJ9.bbcW6HjXuio_ubg8SxkKV1cqgtO36CA80ruxD_hZHV4Dsb_6O4jrXVMIHxoecQGI_zHImJu3ainpONYgE6FZlI1w4hBJWM6Nx5XT5G8XFm252UNOdL29_r8ouyW7uBC9CvebjEDojOqFFi5ZgJdtrQn-a2z3Zs6d9IoPhc8IqLihKTTsLU3_l8j3SKtWI2T5W5VmAxUKhtn_u7dv1R4uP4HjHhseskFSeV0TZcYIeApB9yLgCCjJ_nb9HVuGMIc6wuXS_uOZGrma9Fd2csNzp_yMxXQQyCvf2wL0k_mcmXJ9rrnIGN5qPPdc-K2qtoOg-3XGOzEpCXgJZTuBSlWNdw
Content-Type:application/json


### プロジェクト登録
POST http://localhost:8080/project/
Content-Type:application/json

{
    "userId": 1, 
    "title": "Finish the tutorial on Quarkus framework",
    "registerDate": "2024-06-20",
    "detailList": [
        {
            "taskName": "Read the official documentation"
        },
        {
            "taskName": "Write some example code"
        },
        {
            "taskName": "Build a small project"
        }
    ]
}

### プロジェクト削除
DELETE http://localhost:8080/project/1
Content-Type:application/json
